name: CI

on:
  push:
    branches:
      - main
      - feat/js/add-optimization-module
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4.1.0
    # I install git-crypt into the home environment, so it'll be available once
    # the test script runs, _but_ for the test script to run I have to be able to
    # decrypt secrets.nix, which requires git-crypt.
    # So here only, and anywhere I need to run this in the future, I one-off install
    # git-crypt ahead of time, and use it in the next step to unlock the repo.
    - uses: cachix/install-nix-action@v24
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://cache.iog.io
          trusted-public-keys  = cache.iog.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
    - uses: cachix/cachix-action@v12
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: jisantuc
    - run: nix build
      env:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
